module.exports = {
  acronyms: require('./acronyms.json'),
  areas: require('./areas.json'),
  countries: require('./countries.json'),
  difficulties: ['normal', 'nightmare', 'hell'],
  fbr: require('./fbr.json'),
  fcr: require('./fcr.json'),
  fhr: require('./fhr.json'),
  heroes: require('./heroes.json'),
  hirelings: require('./hirelings.json'),
  itemImages: require('./item-images.json'),
  itemSlots: require('./item-slots.json'),
  items: require('./items.json'),
  levelExperience: require('./level-experience.json'),
  quests: require('./quests.json'),
  recipes: require('./recipes.json'),
  runewords: require('./runewords.json'),
  setItems: require('./set-items.json'),
  sets: require('./sets.json'),
  superUniqueMonsters: require('./super-unique-monsters.json'),
  skills: require('./skills.json'),
  stats: require('./stats.json'),
  unids: require('./unids.json'),
  uniques: require('./uniques.json'),
}
